import "dotenv/config";
import { get_context_for_member, store_transcript } from "./index.js";

async function testFullFlow() {
  console.log("=== Testing Full Backboard + Featherless Flow ===\n");

  const userId = "U09UP83JCAE";
  const conversationId = "conv-123xyz";
  
  // 1. Before the call (Person 2 calls this to get context for ElevenLabs)
  console.log("1. Fetching context for ElevenLabs before the call...");
  const context = await get_context_for_member(userId);
  console.log("\nHistory Context injected into ElevenLabs:");
  console.log(context.historyContext);
  console.log("\n3 Custom Questions generated by Featherless:");
  console.log(context.customQuestions);

  // Simulate the voice call happening...
  console.log("\n---\n(ElevenLabs voice call happens here)\n---\n");

  // 2. After the call (Person 2 webhook receives this transcript)
  const fullTranscript = `agent: Hey janahan, this is your daily sync. Looking at my notes, you were recently focused on API integration. How did that go?
user: Yeah it went well, I finished the endpoint yesterday.
agent: Great! Any blockers today?
user: Still waiting on the design review from the team lead.
agent: Got it. Anything else you're planning to work on today?
user: Going to start on the database migration.`;
  
  // 3. Store and Process (Person 2 calls this to hand off to Person 3)
  console.log("2. Call finished. Processing transcript...");
  console.log(`Transcript:\n${fullTranscript}\n`);
  
  const result = await store_transcript(userId, fullTranscript, conversationId);
  
  // 4. Send to Slack (Person 1 uses this returned string)
  console.log("\n3. Generated Slack Summary (Handed off to Person 1):");
  console.log(result.summaryForSlack);
  
  console.log("\n✅ Full flow completed successfully.");
}

testFullFlow();
