import "dotenv/config";
import { BackboardClient } from "./backboard/client.js";
import { BackboardRepo } from "./backboard/repo.js";
import { StandupService } from "./standup/service.js";
import type { IngestPayload } from "./types.js";

async function testMockData() {
    console.log("Testing with Realistic Mock Data...\n");

    const apiKey = process.env.BACKBOARD_API_KEY;
    if (!apiKey) {
        console.error("❌ BACKBOARD_API_KEY is missing from .env");
        process.exit(1);
    }

    const client = new BackboardClient(apiKey);
    const repo = new BackboardRepo();
    const service = new StandupService(client, repo);

    // This simulates the data we would receive after:
    // 1. ElevenLabs voice call finishes (we get the transcript)
    // 2. Featherless AI processes the transcript to extract structured data 
    const mockPayload: IngestPayload = {
        team_id: "engineering-alpha",
        user_id: "alice-frontend",
        date: "2026-03-01", // "sunday thing"

        // Raw output from ElevenLabs STT
        transcript: "Hey, yesterday I finally finished the authentication flow PR and got it merged. Today I'm starting on the new dashboard components we discussed. The only blocker I have right now is I'm waiting on the final Figma designs from the design team, so I might have to use placeholder styles for now.",

        // Structured JSON extracted by Featherless AI from the transcript
        extracted: {
            yesterday: "Finished and merged authentication flow PR",
            today: "Starting new dashboard components",
            blockers: "Waiting on final Figma designs from design team",
            tasks: ["dashboard-components", "auth-flow"],
            confidence: 0.98
        },

        // Optional summary generated by Featherless AI for the Slack channel
        summary: "Alice finished the auth flow and is starting on dashboards, but is blocked waiting for Figma designs."
    };

    try {
        console.log("Ingesting Alice's Sunday Standup Data:");
        console.log(JSON.stringify(mockPayload, null, 2));
        console.log("\nAttempting to store in Backboard...\n");

        // This will create the assistant (if it doesn't exist), 
        // create the thread for Alice, and store all 3 messages.
        const result = await service.ingest(mockPayload);

        console.log("\n✅ Success! Data stored in Backboard.");
        console.log(`Assistant ID: ${result.assistant_id}`);
        console.log(`Thread ID: ${result.thread_id}`);

        console.log("\nRetrieving the thread to verify what was stored...");
        const thread = await client.getThread(result.thread_id);

        console.log(`\nFound ${thread.messages?.length || 0} messages in thread:`);
        thread.messages?.forEach((msg, i) => {
            console.log(`\n--- Message ${i + 1} (${msg.role}) ---`);
            console.log(msg.content);
        });

    } catch (error) {
        console.error("\n❌ Ingest Failed!");
        console.error(error instanceof Error ? error.message : String(error));
    }
}

testMockData();
