import "dotenv/config";
import { getContextForMember, storeTranscript } from "./index.js";

async function testFullFlow() {
  console.log("=== Testing Full Backboard + Featherless Flow ===\n");

  const teamId = "test-team";
  const userId = "test-user-bob";
  
  // 1. Before the call (Person 2 calls this to get context for ElevenLabs)
  console.log("1. Fetching context for ElevenLabs before the call...");
  const context = await getContextForMember(teamId, userId);
  console.log("\nHistory Context injected into ElevenLabs:");
  console.log(context.historyContext);
  console.log("\n3 Custom Questions generated by Featherless:");
  console.log(context.customQuestions);

  // Simulate the voice call happening...
  console.log("\n---\n(ElevenLabs voice call happens here)\n---\n");

  // 2. After the call (Person 2 webhook receives this transcript)
  const mockTranscript = "Yeah, yesterday I finally figured out that database migration bug. Took way longer than expected. Today I'm just going to be doing code reviews and maybe starting on the new billing API if I have time. No real blockers right now, just need people to approve my PRs.";
  
  // 3. Store and Process (Person 2 calls this to hand off to Person 3)
  console.log("2. Call finished. Processing transcript...");
  console.log(`Transcript: "${mockTranscript}"\n`);
  
  const result = await storeTranscript(teamId, userId, "2026-03-02", mockTranscript);
  
  // 4. Send to Slack (Person 1 uses this returned string)
  console.log("\n3. Generated Slack Summary (Handed off to Person 1):");
  console.log(result.summaryForSlack);
  
  console.log("\n✅ Full flow completed successfully.");
}

testFullFlow();
